{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bd85704e-db9b-4359-a940-73ffdaf8fdcd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: lm-eval[api] in ./jupyter/lib/python3.12/site-packages (0.4.5)\n",
      "Requirement already satisfied: accelerate>=0.26.0 in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (1.1.1)\n",
      "Requirement already satisfied: evaluate in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (0.4.3)\n",
      "Requirement already satisfied: datasets>=2.16.0 in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (3.1.0)\n",
      "Requirement already satisfied: jsonlines in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (4.0.0)\n",
      "Requirement already satisfied: numexpr in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (2.10.1)\n",
      "Requirement already satisfied: peft>=0.2.0 in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (0.13.2)\n",
      "Requirement already satisfied: pybind11>=2.6.2 in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (2.13.6)\n",
      "Requirement already satisfied: pytablewriter in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (1.2.0)\n",
      "Requirement already satisfied: rouge-score>=0.0.4 in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (0.1.2)\n",
      "Requirement already satisfied: sacrebleu>=1.5.0 in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (2.4.3)\n",
      "Requirement already satisfied: scikit-learn>=0.24.1 in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (1.5.2)\n",
      "Requirement already satisfied: sqlitedict in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (2.1.0)\n",
      "Requirement already satisfied: torch>=1.8 in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (2.5.1)\n",
      "Requirement already satisfied: tqdm-multiprocess in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (0.0.11)\n",
      "Requirement already satisfied: transformers>=4.1 in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (4.46.3)\n",
      "Requirement already satisfied: zstandard in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (0.23.0)\n",
      "Requirement already satisfied: dill in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (0.3.8)\n",
      "Requirement already satisfied: word2number in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (1.1)\n",
      "Requirement already satisfied: more-itertools in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (10.5.0)\n",
      "Requirement already satisfied: requests in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (2.32.3)\n",
      "Requirement already satisfied: aiohttp in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (3.11.7)\n",
      "Collecting tenacity (from lm-eval[api])\n",
      "  Downloading tenacity-9.0.0-py3-none-any.whl.metadata (1.2 kB)\n",
      "Requirement already satisfied: tqdm in ./jupyter/lib/python3.12/site-packages (from lm-eval[api]) (4.67.0)\n",
      "Collecting tiktoken (from lm-eval[api])\n",
      "  Downloading tiktoken-0.8.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)\n",
      "Requirement already satisfied: huggingface-hub>=0.21.0 in ./jupyter/lib/python3.12/site-packages (from accelerate>=0.26.0->lm-eval[api]) (0.26.2)\n",
      "Requirement already satisfied: numpy<3.0.0,>=1.17 in ./jupyter/lib/python3.12/site-packages (from accelerate>=0.26.0->lm-eval[api]) (1.26.4)\n",
      "Requirement already satisfied: packaging>=20.0 in ./jupyter/lib/python3.12/site-packages (from accelerate>=0.26.0->lm-eval[api]) (24.2)\n",
      "Requirement already satisfied: psutil in ./jupyter/lib/python3.12/site-packages (from accelerate>=0.26.0->lm-eval[api]) (6.1.0)\n",
      "Requirement already satisfied: pyyaml in ./jupyter/lib/python3.12/site-packages (from accelerate>=0.26.0->lm-eval[api]) (6.0.2)\n",
      "Requirement already satisfied: safetensors>=0.4.3 in ./jupyter/lib/python3.12/site-packages (from accelerate>=0.26.0->lm-eval[api]) (0.4.5)\n",
      "Requirement already satisfied: filelock in ./jupyter/lib/python3.12/site-packages (from datasets>=2.16.0->lm-eval[api]) (3.16.1)\n",
      "Requirement already satisfied: pyarrow>=15.0.0 in ./jupyter/lib/python3.12/site-packages (from datasets>=2.16.0->lm-eval[api]) (18.0.0)\n",
      "Requirement already satisfied: pandas in ./jupyter/lib/python3.12/site-packages (from datasets>=2.16.0->lm-eval[api]) (2.2.3)\n",
      "Requirement already satisfied: xxhash in ./jupyter/lib/python3.12/site-packages (from datasets>=2.16.0->lm-eval[api]) (3.5.0)\n",
      "Requirement already satisfied: multiprocess<0.70.17 in ./jupyter/lib/python3.12/site-packages (from datasets>=2.16.0->lm-eval[api]) (0.70.16)\n",
      "Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in ./jupyter/lib/python3.12/site-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets>=2.16.0->lm-eval[api]) (2024.9.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in ./jupyter/lib/python3.12/site-packages (from requests->lm-eval[api]) (3.4.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in ./jupyter/lib/python3.12/site-packages (from requests->lm-eval[api]) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in ./jupyter/lib/python3.12/site-packages (from requests->lm-eval[api]) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in ./jupyter/lib/python3.12/site-packages (from requests->lm-eval[api]) (2024.8.30)\n",
      "Requirement already satisfied: absl-py in ./jupyter/lib/python3.12/site-packages (from rouge-score>=0.0.4->lm-eval[api]) (2.1.0)\n",
      "Requirement already satisfied: nltk in ./jupyter/lib/python3.12/site-packages (from rouge-score>=0.0.4->lm-eval[api]) (3.9.1)\n",
      "Requirement already satisfied: six>=1.14.0 in ./jupyter/lib/python3.12/site-packages (from rouge-score>=0.0.4->lm-eval[api]) (1.16.0)\n",
      "Requirement already satisfied: portalocker in ./jupyter/lib/python3.12/site-packages (from sacrebleu>=1.5.0->lm-eval[api]) (3.0.0)\n",
      "Requirement already satisfied: regex in ./jupyter/lib/python3.12/site-packages (from sacrebleu>=1.5.0->lm-eval[api]) (2024.11.6)\n",
      "Requirement already satisfied: tabulate>=0.8.9 in ./jupyter/lib/python3.12/site-packages (from sacrebleu>=1.5.0->lm-eval[api]) (0.9.0)\n",
      "Requirement already satisfied: colorama in ./jupyter/lib/python3.12/site-packages (from sacrebleu>=1.5.0->lm-eval[api]) (0.4.6)\n",
      "Requirement already satisfied: lxml in ./jupyter/lib/python3.12/site-packages (from sacrebleu>=1.5.0->lm-eval[api]) (5.3.0)\n",
      "Requirement already satisfied: scipy>=1.6.0 in ./jupyter/lib/python3.12/site-packages (from scikit-learn>=0.24.1->lm-eval[api]) (1.14.1)\n",
      "Requirement already satisfied: joblib>=1.2.0 in ./jupyter/lib/python3.12/site-packages (from scikit-learn>=0.24.1->lm-eval[api]) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in ./jupyter/lib/python3.12/site-packages (from scikit-learn>=0.24.1->lm-eval[api]) (3.5.0)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (4.12.2)\n",
      "Requirement already satisfied: networkx in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (3.4.2)\n",
      "Requirement already satisfied: jinja2 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (3.1.4)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (12.4.127)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (12.4.127)\n",
      "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (12.4.127)\n",
      "Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (9.1.0.70)\n",
      "Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (12.4.5.8)\n",
      "Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (11.2.1.3)\n",
      "Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (10.3.5.147)\n",
      "Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (11.6.1.9)\n",
      "Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (12.3.1.170)\n",
      "Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (2.21.5)\n",
      "Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (12.4.127)\n",
      "Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (12.4.127)\n",
      "Requirement already satisfied: triton==3.1.0 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (3.1.0)\n",
      "Requirement already satisfied: setuptools in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (75.6.0)\n",
      "Requirement already satisfied: sympy==1.13.1 in ./jupyter/lib/python3.12/site-packages (from torch>=1.8->lm-eval[api]) (1.13.1)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./jupyter/lib/python3.12/site-packages (from sympy==1.13.1->torch>=1.8->lm-eval[api]) (1.3.0)\n",
      "Requirement already satisfied: tokenizers<0.21,>=0.20 in ./jupyter/lib/python3.12/site-packages (from transformers>=4.1->lm-eval[api]) (0.20.3)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in ./jupyter/lib/python3.12/site-packages (from aiohttp->lm-eval[api]) (2.4.3)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in ./jupyter/lib/python3.12/site-packages (from aiohttp->lm-eval[api]) (1.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in ./jupyter/lib/python3.12/site-packages (from aiohttp->lm-eval[api]) (24.2.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in ./jupyter/lib/python3.12/site-packages (from aiohttp->lm-eval[api]) (1.5.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in ./jupyter/lib/python3.12/site-packages (from aiohttp->lm-eval[api]) (6.1.0)\n",
      "Requirement already satisfied: propcache>=0.2.0 in ./jupyter/lib/python3.12/site-packages (from aiohttp->lm-eval[api]) (0.2.0)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in ./jupyter/lib/python3.12/site-packages (from aiohttp->lm-eval[api]) (1.18.0)\n",
      "Requirement already satisfied: DataProperty<2,>=1.0.1 in ./jupyter/lib/python3.12/site-packages (from pytablewriter->lm-eval[api]) (1.0.1)\n",
      "Requirement already satisfied: mbstrdecoder<2,>=1.0.0 in ./jupyter/lib/python3.12/site-packages (from pytablewriter->lm-eval[api]) (1.1.3)\n",
      "Requirement already satisfied: pathvalidate<4,>=2.3.0 in ./jupyter/lib/python3.12/site-packages (from pytablewriter->lm-eval[api]) (3.2.1)\n",
      "Requirement already satisfied: tabledata<2,>=1.3.1 in ./jupyter/lib/python3.12/site-packages (from pytablewriter->lm-eval[api]) (1.3.3)\n",
      "Requirement already satisfied: tcolorpy<1,>=0.0.5 in ./jupyter/lib/python3.12/site-packages (from pytablewriter->lm-eval[api]) (0.1.6)\n",
      "Requirement already satisfied: typepy<2,>=1.3.2 in ./jupyter/lib/python3.12/site-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter->lm-eval[api]) (1.3.2)\n",
      "Requirement already satisfied: chardet<6,>=3.0.4 in ./jupyter/lib/python3.12/site-packages (from mbstrdecoder<2,>=1.0.0->pytablewriter->lm-eval[api]) (5.2.0)\n",
      "Requirement already satisfied: python-dateutil<3.0.0,>=2.8.0 in ./jupyter/lib/python3.12/site-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter->lm-eval[api]) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2018.9 in ./jupyter/lib/python3.12/site-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter->lm-eval[api]) (2024.2)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in ./jupyter/lib/python3.12/site-packages (from jinja2->torch>=1.8->lm-eval[api]) (3.0.2)\n",
      "Requirement already satisfied: click in ./jupyter/lib/python3.12/site-packages (from nltk->rouge-score>=0.0.4->lm-eval[api]) (8.1.7)\n",
      "Requirement already satisfied: tzdata>=2022.7 in ./jupyter/lib/python3.12/site-packages (from pandas->datasets>=2.16.0->lm-eval[api]) (2024.2)\n",
      "Downloading tenacity-9.0.0-py3-none-any.whl (28 kB)\n",
      "Downloading tiktoken-0.8.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.2/1.2 MB\u001b[0m \u001b[31m9.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m[31m12.1 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: tenacity, tiktoken\n",
      "Successfully installed tenacity-9.0.0 tiktoken-0.8.0\n"
     ]
    }
   ],
   "source": [
    "!pip install \"lm-eval\"\n",
    "!pip install \"lm-eval[api]\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "ec558c04-ab1e-4567-93a5-b9c6496419fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "key_path = 'goodfire_api_key.txt'\n",
    "with open(key_path, 'r') as file:\n",
    "    GOODFIRE_API_KEY = file.read().strip()\n",
    "    os.environ['OPENAI_API_KEY'] = GOODFIRE_API_KEY\n",
    "api_url=\"https://api.goodfire.ai/api/inference/v1/chat/completions\""
   ]
  },
  {
   "cell_type": "markdown",
   "id": "00f2461b-c9b6-46ff-ba41-e5b1d7c072b1",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "a68aad60-43ff-4c7e-9aa8-486f9995f17c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-11-23:16:42:24,237 INFO     [__main__.py:279] Verbosity set to INFO\n",
      "2024-11-23:16:42:27,610 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.\n",
      "2024-11-23:16:42:27,620 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.\n",
      "2024-11-23:16:42:27,650 INFO     [__main__.py:376] Selected Tasks: ['mmlu_flan_n_shot_generative_college_computer_science', 'mmlu_flan_n_shot_generative_computer_security']\n",
      "2024-11-23:16:42:27,650 INFO     [evaluator.py:164] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234 | Setting fewshot manual seed to 1234\n",
      "2024-11-23:16:42:27,650 INFO     [evaluator.py:201] Initializing openai-chat-completions model, with arguments: {'model': 'meta-llama/Meta-Llama-3-8B-Instruct', 'tokenized_requests': False, 'base_url': 'https://api.goodfire.ai/api/inference/v1/chat/completions', 'num_concurrent': 25}\n",
      "2024-11-23:16:42:27,650 WARNING  [openai_completions.py:106] chat-completions endpoint requires the `--apply_chat_template` flag.\n",
      "2024-11-23:16:42:27,650 INFO     [api_models.py:111] Using max length 2048 - 1\n",
      "2024-11-23:16:42:27,650 INFO     [api_models.py:124] Using tokenizer None\n",
      "2024-11-23:16:42:29,664 WARNING  [evaluator.py:270] Overwriting default num_fewshot of mmlu_flan_n_shot_generative_computer_security from None to 0\n",
      "2024-11-23:16:42:29,664 WARNING  [evaluator.py:270] Overwriting default num_fewshot of mmlu_flan_n_shot_generative_college_computer_science from None to 0\n",
      "2024-11-23:16:42:29,664 INFO     [task.py:415] Building contexts for mmlu_flan_n_shot_generative_computer_security on rank 0...\n",
      "100%|██████████████████████████████████████| 100/100 [00:00<00:00, 1268.64it/s]\n",
      "2024-11-23:16:42:29,745 INFO     [task.py:415] Building contexts for mmlu_flan_n_shot_generative_college_computer_science on rank 0...\n",
      "100%|██████████████████████████████████████| 100/100 [00:00<00:00, 1231.64it/s]\n",
      "2024-11-23:16:42:29,829 INFO     [evaluator.py:489] Running generate_until requests\n",
      "Requesting API:  36%|█████████▏               | 73/200 [00:44<01:22,  1.55it/s]2024-11-23:16:43:15,796 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: 1DCWCAqZZdc4wibZgVdtkUR0q_-RvWm4TEsAR5gC26BNAVDHPLGnsA==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  42%|██████████▌              | 84/200 [00:51<00:52,  2.21it/s]2024-11-23:16:43:22,527 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: IEsZDjI7ciEydc-4oV29qjL8nHJ_ClYnJyX1mUjYPgcI3KJObRqLfA==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  42%|██████████▋              | 85/200 [00:52<01:19,  1.45it/s]2024-11-23:16:43:23,142 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: OzBMSKTpPepk0_cwhsoc34A14yPq3oo-dXkOPe1UtPQGb606L4sMxA==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  44%|██████████▉              | 87/200 [00:54<01:23,  1.35it/s]2024-11-23:16:43:24,471 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: 21gC4Uqdg1WUXgDhixc21WyEPQBcx_PBcp7ZmxxgHQHpZPnRSqmfMQ==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "2024-11-23:16:43:25,859 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: CyPRij0Bflc3LOdrhDl7NB0j_br4hSweSYesW17WHowfn3tBKrzeBA==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  46%|███████████▌             | 92/200 [00:59<01:39,  1.08it/s]2024-11-23:16:43:31,855 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: RrJkgXCrafUVt5zZ50Q91h8xvAJMF1U7CiwbgWYMqD5yvmEcmlK37A==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  49%|████████████▎            | 98/200 [01:07<01:58,  1.17s/it]2024-11-23:16:43:38,236 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: OWYxNLiECGVBlVgD_OYNVgf9-5It6HGjgY92XW-Wk1sMDuOY7MVXNw==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  50%|████████████            | 100/200 [01:08<01:21,  1.23it/s]2024-11-23:16:43:40,400 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: MsXUnIDVS0iyKfxPtgyncMB3CySc_bLFg2CDwqQArScGSr5T4Es1yw==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  52%|████████████▍           | 104/200 [01:12<01:19,  1.21it/s]2024-11-23:16:43:44,088 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: BQSl5VsnBaEri1tcJ5NGGQcsdUgVL-LLGsoCLZMAD9asv4T8hl7xpg==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  52%|████████████▌           | 105/200 [01:16<02:40,  1.69s/it]2024-11-23:16:43:47,365 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: Ca_KAdlqD5teXXA8a01HZxjpL9uvnabr-D3N8pwKrZBxQGzfKCaUuw==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "2024-11-23:16:43:47,365 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: Hewyk6KvXL87EZ7FwcT8_CQDmOtya-PKdRiWTY0N1D_FozYQZTnK0g==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "2024-11-23:16:43:50,435 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: MQsIZh_uE9umbsUc3MPHcxoBHaVfi_0m2haejuXGY_Xt1w4faTgKYQ==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "2024-11-23:16:43:50,435 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: NVI84LqGzi1sdEOAXhUbZkGLf4iMIsPzJaU1LPA4jxlKCDTB5GPWNA==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "2024-11-23:16:43:50,743 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: RMDjPPKtwK1Ge8IegUrXB1RCc-x7h0zoL0j_j-XipI6guGsLnLCq_A==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  54%|████████████▉           | 108/200 [01:22<02:59,  1.95s/it]2024-11-23:16:43:52,894 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: S-AxPM4sRzT-6Bv7TdRpq-v7eou3mOf6FlhYP-P0erqe4VNP-qIMvA==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  57%|█████████████▋          | 114/200 [01:26<01:13,  1.17it/s]2024-11-23:16:43:57,296 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: gFk8LOUKnYLRmJIrzDQlYWJn6dYK7bPPz6kWUvue_ojOo2h-NMY_CA==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "2024-11-23:16:43:57,807 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: s5xy6oAUyUH32n949j3eaa7nIeEPG5ZQu524ri_oDEAnuEdcAjhPYQ==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "2024-11-23:16:43:57,830 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: _e-weyN8SfEIj2XO_VUmFXqjg-kqIldQxeC-T8mTGwpQ2Vlx_lLckQ==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  59%|██████████████▏         | 118/200 [01:32<01:46,  1.30s/it]2024-11-23:16:44:03,030 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: GH1iO4svCWR-yyo8nh09QxW7NQbwdXDTJt-maRlkb2GJzMj_zipnTg==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  63%|███████████████         | 126/200 [01:38<00:53,  1.38it/s]2024-11-23:16:44:08,559 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: __RrnSA9g3PyT530rHh8UZ8CPlEr3ALG8yb5nh3NVkNK9Ir8TD29dw==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  64%|███████████████▍        | 129/200 [01:40<00:50,  1.40it/s]2024-11-23:16:44:11,120 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: _NSuioaq2vjQPnSNBFKmF3lsxUPE8P80_LlpmJwboFeTStxRQPaoEQ==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  66%|███████████████▊        | 132/200 [01:43<01:00,  1.13it/s]2024-11-23:16:44:14,294 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: IdgOULT08gq6gsVGdF_183bZouTKfPdb-I9gKy7tlB0JWHYI_EpoWw==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  68%|████████████████▏       | 135/200 [01:45<00:38,  1.70it/s]2024-11-23:16:44:16,081 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: _h-FRQ1yOR9wEuQqYnYHka2J22KUc3phLYHjgKUtltCKXHWkH80vxw==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "2024-11-23:16:44:17,574 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: tr9trT0g3tXfqA2Gv86caBkaPpIVOR4XOa8bgYD4LjdY78h_OaPKfw==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  70%|████████████████▉       | 141/200 [01:54<01:03,  1.07s/it]2024-11-23:16:44:24,227 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: R2VujTrMUtjvEWhEb_GNefekZS5wkjMK4v1_pkKEPMi4N9GDFYya8Q==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  72%|█████████████████▍      | 145/200 [01:57<00:47,  1.16it/s]2024-11-23:16:44:27,980 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: tXnv5Up9WhLk5LY_Fu5_kLiquuu-9GbhYfZbSdpAyzPvzLv-6-OSaw==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  74%|█████████████████▉      | 149/200 [02:02<01:14,  1.45s/it]2024-11-23:16:44:32,420 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: ht3slniqXeWB7qt-vF7BNk5zBAVUl8iuaKnlg25vIsWBaVtj6yZELA==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API: 100%|████████████████████████| 200/200 [02:28<00:00,  1.35it/s]\n",
      "2024-11-23:16:45:00,976 INFO     [evaluation_tracker.py:206] Saving results aggregated\n",
      "2024-11-23:16:45:00,977 INFO     [evaluation_tracker.py:287] Saving per-sample results for: mmlu_flan_n_shot_generative_college_computer_science\n",
      "2024-11-23:16:45:00,985 INFO     [evaluation_tracker.py:287] Saving per-sample results for: mmlu_flan_n_shot_generative_computer_security\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "openai-chat-completions (model=meta-llama/Meta-Llama-3-8B-Instruct,tokenized_requests=False,base_url=https://api.goodfire.ai/api/inference/v1/chat/completions,num_concurrent=25), gen_kwargs: (None), limit: None, num_fewshot: 0, batch_size: 1\n",
      "|                       Tasks                        |Version|     Filter     |n-shot|  Metric   |   |Value|   |Stderr|\n",
      "|----------------------------------------------------|------:|----------------|-----:|-----------|---|----:|---|-----:|\n",
      "|mmlu_flan_n_shot_generative_college_computer_science|      3|flexible-extract|     0|exact_match|↑  | 0.47|±  |0.0502|\n",
      "|                                                    |       |strict-match    |     0|exact_match|↑  | 0.00|±  |0.0000|\n",
      "|mmlu_flan_n_shot_generative_computer_security       |      3|flexible-extract|     0|exact_match|↑  | 0.62|±  |0.0488|\n",
      "|                                                    |       |strict-match    |     0|exact_match|↑  | 0.00|±  |0.0000|\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "CompletedProcess(args=['lm_eval', '--model', 'openai-chat-completions', '--model_args', 'model=meta-llama/Meta-Llama-3-8B-Instruct,tokenized_requests=False,base_url=https://api.goodfire.ai/api/inference/v1/chat/completions,num_concurrent=25', '--tasks', 'mmlu_flan_n_shot_generative_college_computer_science,mmlu_flan_n_shot_generative_computer_security', '--log_samples', '--apply_chat_template', 'True', '--num_fewshot', '0', '--output_path', 'out_example'], returncode=0)"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import subprocess\n",
    "\n",
    "subprocess.run([\n",
    "    'lm_eval',\n",
    "    '--model', 'openai-chat-completions',\n",
    "    '--model_args', f'model=meta-llama/Meta-Llama-3-8B-Instruct,tokenized_requests=False,base_url={api_url},num_concurrent=25',\n",
    "    '--tasks', 'mmlu_flan_n_shot_generative_college_computer_science,mmlu_flan_n_shot_generative_computer_security',\n",
    "    '--log_samples',\n",
    "    '--apply_chat_template', 'True',\n",
    "    '--num_fewshot', '0',\n",
    "    '--output_path', 'out_example'\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "273a65eb-4fdd-4b09-8916-545339b409b0",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-11-23:17:40:44,413 INFO     [__main__.py:279] Verbosity set to INFO\n",
      "2024-11-23:17:40:47,509 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.\n",
      "2024-11-23:17:40:47,518 INFO     [__init__.py:459] The tag 'arc_ca' is already registered as a group, this tag will not be registered. This may affect tasks you want to call.\n",
      "2024-11-23:17:40:47,547 INFO     [__main__.py:376] Selected Tasks: ['mmlu_flan_n_shot_generative_college_biology', 'mmlu_flan_n_shot_generative_virology']\n",
      "2024-11-23:17:40:47,548 INFO     [evaluator.py:164] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234 | Setting fewshot manual seed to 1234\n",
      "2024-11-23:17:40:47,548 INFO     [evaluator.py:201] Initializing openai-chat-completions model, with arguments: {'model': 'meta-llama/Meta-Llama-3-8B-Instruct', 'tokenized_requests': False, 'base_url': 'https://api.goodfire.ai/api/inference/v1/chat/completions', 'num_concurrent': 10}\n",
      "2024-11-23:17:40:47,548 WARNING  [openai_completions.py:106] chat-completions endpoint requires the `--apply_chat_template` flag.\n",
      "2024-11-23:17:40:47,548 INFO     [api_models.py:111] Using max length 2048 - 1\n",
      "2024-11-23:17:40:47,548 INFO     [api_models.py:124] Using tokenizer None\n",
      "2024-11-23:17:40:49,403 WARNING  [evaluator.py:270] Overwriting default num_fewshot of mmlu_flan_n_shot_generative_virology from None to 0\n",
      "2024-11-23:17:40:49,403 WARNING  [evaluator.py:270] Overwriting default num_fewshot of mmlu_flan_n_shot_generative_college_biology from None to 0\n",
      "2024-11-23:17:40:49,403 INFO     [task.py:415] Building contexts for mmlu_flan_n_shot_generative_virology on rank 0...\n",
      "100%|██████████████████████████████████████| 166/166 [00:00<00:00, 1356.11it/s]\n",
      "2024-11-23:17:40:49,530 INFO     [task.py:415] Building contexts for mmlu_flan_n_shot_generative_college_biology on rank 0...\n",
      "100%|██████████████████████████████████████| 144/144 [00:00<00:00, 1315.14it/s]\n",
      "2024-11-23:17:40:49,643 INFO     [evaluator.py:489] Running generate_until requests\n",
      "Requesting API:   8%|██                       | 25/310 [00:39<05:16,  1.11s/it]2024-11-23:17:41:30,960 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: EpuPugzKjHNWumH2q4tKyLo-IVEIDUqJKA2Mi2VAPvul1jDkvR_bYQ==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "2024-11-23:17:41:31,266 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: iFyctOxA8v_78cbn9AXC7XEBd3R35WnBo8Kl6tUhs1Qm_N53ye087g==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "2024-11-23:17:41:33,007 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: avPKVnzs2zgnl5n7-o3JcW8F_mxtw5RHXaBHjZZlRKPtjByujG73cg==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  13%|███▏                     | 39/310 [01:02<07:18,  1.62s/it]2024-11-23:17:41:53,078 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: BZILTuI5tMeZx-awzodwpS-qa4saPZkOVN_zuZbwwitb-YdTCXNMNA==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  13%|███▎                     | 41/310 [01:05<06:40,  1.49s/it]2024-11-23:17:41:55,252 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: GklADnGRC-J3FyGutX2ts3otW-kjdydKH2li_ruvH6x9BT16g0EnOg==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "2024-11-23:17:41:56,254 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: BriS8RfBBGtXkA9Ckh2hecPuCBuUIOL8VyYhvkFYbap1NoaInlK_eA==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API:  16%|████                     | 51/310 [01:18<02:13,  1.94it/s]2024-11-23:17:42:08,540 WARNING  [api_models.py:390] API request failed with error message: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n",
      "<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n",
      "<TITLE>ERROR: The request could not be satisfied</TITLE>\n",
      "</HEAD><BODY>\n",
      "<H1>504 ERROR</H1>\n",
      "<H2>The request could not be satisfied.</H2>\n",
      "<HR noshade size=\"1px\">\n",
      "CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\n",
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n",
      "<BR clear=\"all\">\n",
      "If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n",
      "<BR clear=\"all\">\n",
      "<HR noshade size=\"1px\">\n",
      "<PRE>\n",
      "Generated by cloudfront (CloudFront)\n",
      "Request ID: SFrb8gKH5Ab8uwDTnCwqYpu7X0hxA8NUO7JUXh5p_a6m7IpSf7pmxw==\n",
      "</PRE>\n",
      "<ADDRESS>\n",
      "</ADDRESS>\n",
      "</BODY></HTML>. Retrying...\n",
      "Requesting API: 100%|████████████████████████| 310/310 [06:49<00:00,  1.32s/it]\n",
      "2024-11-23:17:47:42,303 INFO     [evaluation_tracker.py:206] Saving results aggregated\n",
      "2024-11-23:17:47:42,303 INFO     [evaluation_tracker.py:287] Saving per-sample results for: mmlu_flan_n_shot_generative_college_biology\n",
      "2024-11-23:17:47:42,311 INFO     [evaluation_tracker.py:287] Saving per-sample results for: mmlu_flan_n_shot_generative_virology\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "openai-chat-completions (model=meta-llama/Meta-Llama-3-8B-Instruct,tokenized_requests=False,base_url=https://api.goodfire.ai/api/inference/v1/chat/completions,num_concurrent=10), gen_kwargs: (None), limit: None, num_fewshot: 0, batch_size: 1\n",
      "|                   Tasks                   |Version|     Filter     |n-shot|  Metric   |   |Value |   |Stderr|\n",
      "|-------------------------------------------|------:|----------------|-----:|-----------|---|-----:|---|-----:|\n",
      "|mmlu_flan_n_shot_generative_college_biology|      3|flexible-extract|     0|exact_match|↑  |0.6944|±  |0.0385|\n",
      "|                                           |       |strict-match    |     0|exact_match|↑  |0.0000|±  |0.0000|\n",
      "|mmlu_flan_n_shot_generative_virology       |      3|flexible-extract|     0|exact_match|↑  |0.4639|±  |0.0388|\n",
      "|                                           |       |strict-match    |     0|exact_match|↑  |0.0000|±  |0.0000|\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "CompletedProcess(args=['lm_eval', '--model', 'openai-chat-completions', '--model_args', 'model=meta-llama/Meta-Llama-3-8B-Instruct,tokenized_requests=False,base_url=https://api.goodfire.ai/api/inference/v1/chat/completions,num_concurrent=10', '--tasks', 'mmlu_flan_n_shot_generative_college_biology,mmlu_flan_n_shot_generative_virology', '--log_samples', '--apply_chat_template', 'True', '--num_fewshot', '0', '--output_path', 'out_example'], returncode=0)"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import subprocess\n",
    "\n",
    "subprocess.run([\n",
    "    'lm_eval',\n",
    "    '--model', 'openai-chat-completions',\n",
    "    '--model_args', f'model=meta-llama/Meta-Llama-3-8B-Instruct,tokenized_requests=False,base_url={api_url},num_concurrent=10',\n",
    "    '--tasks', 'mmlu_flan_n_shot_generative_college_biology,mmlu_flan_n_shot_generative_virology',\n",
    "    '--log_samples',\n",
    "    '--apply_chat_template', 'True',\n",
    "    '--num_fewshot', '0',\n",
    "    '--output_path', 'out_example'\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c49edc57-cf99-4087-8d17-836722dddac3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
